// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMC9I1YQ_bBj_OT44DWcipZ8K621O6fY',
    appId: '1:31893954334:android:3b0c7ff8546e138078330f',
    messagingSenderId: '31893954334',
    projectId: 'magic-share-backend',
    storageBucket: 'magic-share-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKdPhWSvAuHA2k0vi21b5IyaDIxzThG20',
    appId: '1:31893954334:ios:0d5c5906b7aa590678330f',
    messagingSenderId: '31893954334',
    projectId: 'magic-share-backend',
    storageBucket: 'magic-share-backend.firebasestorage.app',
    iosBundleId: 'com.magicshare.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKdPhWSvAuHA2k0vi21b5IyaDIxzThG20',
    appId: '1:31893954334:ios:0d5c5906b7aa590678330f',
    messagingSenderId: '31893954334',
    projectId: 'magic-share-backend',
    storageBucket: 'magic-share-backend.firebasestorage.app',
    iosBundleId: 'com.magicshare.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYD2SApw9hOEHi070P-KcjrFXncLtnD6M',
    appId: '1:31893954334:web:bd65792bb58c01ae78330f',
    messagingSenderId: '31893954334',
    projectId: 'magic-share-backend',
    authDomain: 'magic-share-backend.firebaseapp.com',
    storageBucket: 'magic-share-backend.firebasestorage.app',
    measurementId: 'G-605JYSTLD0',
  );
}
