display_name: MagicShare
packager: MagicShare contributors
packagerEmail: noreply@magicshare.invalid
url: https://github.com/mekedron/MagicShare
buildArch: x86_64
license: MIT

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: Cloud-assisted device sync built on top of LocalSend.
summary: Share files easily with MagicShare
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
